version: '3.8'

services:
  database:
    container_name: mouserace-database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_TCP_PORT=3306
      - MYSQL_DATABASE=mouserace
    ports:
      - 3306:3306
    build: ./database 
    volumes:
      - mouserace-database:/var/lib/mysql
  backend:
    depends_on:
      - database
    container_name: mouserace-backend
    ports:
      - 8082:8082
    environment:
      - NODE_ENV=compose
    build: ./backend
  frontend:
    depends_on:
      - backend
    container_name: mouserace-frontend
    ports:
      - 3000:80
    build: ./frontend

volumes:
  mouserace-database: